
language: android
jdk: oraclejdk7

android:
  components:
     - platform-tool
     - android-22
     - build-tools-22.0.1

sudo: false
notifications:
  email: false

script:
  - ./gradlew clean build