
language: android
jdk: oraclejdk7

android:
  components:
     - platform-tools
     - android-23
     - build-tools-22.0.1
     - extra

sudo: false
notifications:
  email: false

script:
  - ./gradlew clean build