
language: android
jdk: oraclejdk7

install:
  - npm install -g underscore-cli
  - sudo pip install transifex-client
android:
  components:
     - android-22
     - build-tools-22.0.1
     - extra-android-m2repository


notifications:
  email: false

script:
  - ./locales-push.sh
  - ./gradlew clean build
