
language: android
jdk: oraclejdk7

before_install:
    -git clone --depth=1 https://github.com/PanicInitiative/panicbutton.io
    
install:
  - npm install -g underscore-cli
  - sudo pip install transifex-client
  
android:
  components:
     - android-22
     - build-tools-22.0.1
     - extra-android-m2repository


notifications:
  email: false

script:
  - ./locales/locales-push.sh
  - ./locales/tx init
  - ./locales/tx set --auto-local --type KEYVALUEJSON -r panicbutton.mobile 'mobile.<lang>.json' --source-lang en --execute
  - ./gradlew clean build
