language: android
jdk: oraclejdk7
env:
  global:
    - ANDROID_API_LEVEL=android-21
    - ANDROID_ABI=armeabi-v7a
android:
  components:

    # The BuildTools version used by your project
    - build-tools-22.0.1

    # The SDK version used to compile your project
    - android-22
licenses:
    - android-sdk-license-5be876d5 # new license!
    - 'android-sdk-license-.+'

script:
  - ./gradlew test